wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.10
    framework: huggingface
    huggingface_version: 4.24.0
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.8.1
    start_time: 1677259920.838449
    t:
      1:
      - 1
      - 5
      - 11
      - 33
      - 49
      - 53
      - 55
      - 77
      2:
      - 1
      - 5
      - 11
      - 33
      - 49
      - 53
      - 55
      - 77
      3:
      - 23
      4: 3.8.1
      5: 0.13.10
      6: 4.24.0
      8:
      - 3
      - 5
